public class Pokemon {
    @auraEnabled
    public string name;
    @auraEnabled
	public string base_experience;
	@auraEnabled
    public string location_area_encounters;
    @auraEnabled
    public string Id;
    @auraEnabled
    public string height;
    @auraEnabled
    public List<Abilities> abilities;
    @auraEnabled
    public string weight;
    @auraEnabled
    public List<Stats> Stats;
    @auraEnabled
    public List<types> types;
}